doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Domains/DoctrineMigrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: App\Domains\DoctrineMigrations
